[workspace]
resolver = "3"
members = [
    "common",
    "core",
    "skyblock_tools"
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
reqwest = { version = "0.12.24", features = ["json", "gzip", "brotli", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
phf = { version = "0.13.1", features = ["macros"] }
rsa = { version = "0.10.0-rc.10", features = ["sha1", "sha2"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
sqlx = { version = "0.9.0-alpha.1", features = ["runtime-tokio", "postgres", "uuid", "json", "chrono", "macros"] }
tracing-subscriber = { version = "0.3.20", features = ["json", "env-filter"]}
tracing = "0.1.41"
tracing-appender = "0.2.3"
sha1 = "0.11.0-rc.3"
sha2 = "0.11.0-rc.3"
dotenvy = "0.15.7"
once_cell = "1.21.3"
rustc-hash = "2.1.1"
futures-util = "0.3.31"
futures = "0.3.31"
fastnbt = "2.6.0"
base64 = "0.22.1"
flate2 = "1.1.5"
async-trait = "0.1.89"
axum = "0.8.6"
chrono = "0.4.42"
git2 = "0.20.2"
dotenv = "0.15.0"
derive-new = "0.7.0"
getset = "0.1.6"
tantivy = "0.25.0"