use phf::{phf_map, phf_set, Map, Set};

pub static REFORGE_STONES: Map<&'static str, &'static str> = phf_map! {
    "stiff" => "HARDENED_WOOD",
    "trashy" => "OVERFLOWING_TRASH_CAN",
    "salty" => "SALT_CUBE",
    "aote_stone" => "AOTE_STONE",
    "warped" => "AOTE_STONE",
    "blazing" => "BLAZEN_SPHERE",
    "waxed" => "BLAZE_WAX",
    "rooted" => "BURROWING_SPORES",
    "calcified" => "CALCIFIED_HEART",
    "candied" => "CANDY_CORN",
    "perfect" => "DIAMOND_ATOM",
    "fleet" => "DIAMONITE",
    "fabled" => "DRAGON_CLAW",
    "spiked" => "DRAGON_SCALE",
    "royal" => "DWARVEN_TREASURE",
    "hyper" => "ENDSTONE_GEODE",
    "coldfusion" => "ENTROPY_SUPPRESSOR",
    "blooming" => "FLOWERING_BOUQUET",
    "fanged" => "FULL_JAW_FANGING_KIT",
    "jaded" => "JADERALD",
    "jerry_stone" => "JERRY_STONE",
    "magnetic" => "LAPIS_CRYSTAL",
    "earthy" => "LARGE_WALNUT",
    "groovy" => "MANGROVE_GEM",
    "fortified" => "METEOR_SHARD",
    "gilded" => "MIDAS_JEWEL",
    "moonglade" => "MOONGLADE_JEWEL",
    "cubic" => "MOLTEN_CUBE",
    "necrotic" => "NECROMANCER_BROOCH",
    "fruitful" => "ONYX",
    "precise" => "OPTICAL_LENS",
    "mossy" => "OVERGROWN_GRASS",
    "pitchin" => "PITCHIN_KOI",
    "undead" => "PREMIUM_FLESH",
    "blood_soaked" => "PRESUMED_GALLON_OF_RED_PAINT",
    "mithraic" => "PURE_MITHRIL",
    "reinforced" => "RARE_DIAMOND",
    "ridiculous" => "RED_NOSE",
    "loving" => "RED_SCARF",
    "auspicious" => "ROCK_GEMSTONE",
    "treacherous" => "RUSTY_ANCHOR",
    "headstrong" => "SALMON_OPAL",
    "strengthened" => "SEARING_STONE",
    "glistening" => "SHINY_PRISM",
    "bustling" => "SKYMART_BROCHURE",
    "spiritual" => "SPIRIT_DECOY",
    "squeaky" => "SQUEAKY_TOY",
    "suspicious" => "SUSPICIOUS_VIAL",
    "snowy" => "TERRY_SNOWGLOBE",
    "dimensional" => "TITANIUM_TESSERACT",
    "ambered" => "AMBER_MATERIAL",
    "beady" => "BEADY_EYES",
    "blessed" => "BLESSED_FRUIT",
    "bulky" => "BULKY_STONE",
    "buzzing" => "CLIPPED_WINGS",
    "submerged" => "DEEP_SEA_ORB",
    "renowned" => "DRAGON_HORN",
    "festive" => "FROZEN_BAUBLE",
    "giant" => "GIANT_TOOTH",
    "lustrous" => "GLEAMING_CRYSTAL",
    "bountiful" => "GOLDEN_BALL",
    "chomp" => "KUUDRA_MANDIBLE",
    "lucky" => "LUCKY_DICE",
    "stellar" => "PETRIFIED_STARFALL",
    "scraped" => "POCKET_ICEBERG",
    "ancient" => "PRECURSOR_GEAR",
    "refined" => "REFINED_AMBER",
    "empowered" => "SADAN_BROOCH",
    "withered" => "WITHER_BLOOD",
    "glacial" => "FRIGID_HUSK",
    "heated" => "HOT_STUFF",
    "bloodshot" => "SHRIVELED_CORNEA",
    "blood_shot" => "SHRIVELED_CORNEA",
};

pub static EXECLUDE_REFORGES: Set<&'static str> = phf_set! {
    "none",
    "fair",
    "epic",
    "fast",
    "gentle",
    "heroic",
    "legendary",
    "odd",
    "odd_sword",
    "sharp",
    "spicy",
    "awkward",
    "deadly",
    "fine",
    "grand",
    "hasty",
    "neat",
    "rich",
    "unreal",
    "clean",
    "fierce",
    "heavy",
    "light",
    "mythic",
    "pure",
    "smart",
    "titanic",
    "wise",
    "astute",
    "blended",
    "brilliant",
    "colossal",
    "hefty",
    "honored",
    "menacing",
    "soft",
    "stained",
    "unyielding",
    "excellent",
    "fortunate",
    "sturdy",
    "prospector's",
    "great",
    "lush",
    "rugged",
    "double_bit",
    "lumberjack",
    "green_thumb",
    "robust",
    "zooming",
    "peasant's",
    "rich_bow",
    "rapid",
    "unpleasant",
    "strange",
    "shaded",
    "vivid",
    "zealous",
    "prospector",
    "godly",
    "forceful",
    "strong",
    "bizarre",
    "hurtful",
    "superior",
    "itchy",
    "demonic",
    "bloody",
    "shiny",
    "pleasant",
    "peasant",
    "silky",
    "keen"
};

pub static NPC_REFORGES: Map<&'static str, f64> = phf_map! {
    "greater_spook" => 10000.0,
    "moil" => 50000.0,
    "toil" => 1000000.0,
    "dirty" => 100000.0
};