#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub enum SetupType {
    Mining,
    Farming,
    Foraging,
    Fishing,
    Archer,
    Berserker,
    Mage,
    Tank,
    Healer,
}

impl SetupType {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "Mining" => Some(SetupType::Mining),
            "Farming" => Some(SetupType::Farming),
            "Foraging" => Some(SetupType::Foraging),
            "Fishing" => Some(SetupType::Fishing),
            "Archer" => Some(SetupType::Archer),
            "Berserker" => Some(SetupType::Berserker),
            "Mage" => Some(SetupType::Mage),
            "Tank" => Some(SetupType::Tank),
            "Healer" => Some(SetupType::Healer),
            _ => None,
        }
    }

    pub fn get_setup(&self) -> &'static Setup {
        match self {
            SetupType::Mining => &MINING_SETUP,
            SetupType::Farming => &FARMING_SETUP,
            SetupType::Foraging => &FORAGING_SETUP,
            SetupType::Fishing => &FISHING_SETUP,
            SetupType::Archer => &ARCHER_SETUP,
            SetupType::Berserker => &BERSERKER_SETUP,
            SetupType::Mage => &MAGE_SETUP,
            SetupType::Tank => &TANK_SETUP,
            SetupType::Healer => &HEALER_SETUP,
        }
    }
}

#[derive(Debug)]
pub struct Setup {
    pub armor: &'static [&'static [&'static str]],
    pub equipment: &'static [&'static [&'static str]],
    pub tools: &'static [&'static [&'static str]],
    pub pets: &'static [&'static str],
}

pub const MINING_SETUP: Setup = Setup {
    armor: &[
        &["DIVAN_HELMET", "DIVAN_CHESTPLATE", "DIVAN_LEGGINGS", "DIVAN_BOOTS"],
        &["SORROW_HELMET", "SORROW_CHESTPLATE", "SORROW_LEGGINGS", "SORROW_BOOTS"],
        &["ARMOR_OF_YOG_HELMET", "ARMOR_OF_YOG_CHESTPLATE", "ARMOR_OF_YOG_LEGGINGS", "ARMOR_OF_YOG_BOOTS"],
        &["FLAME_BREAKER_HELMET", "FLAME_BREAKER_CHESTPLATE", "FLAME_BREAKER_LEGGINGS", "FLAME_BREAKER_BOOTS"],
        &["HEAT_HELMET", "HEAT_CHESTPLATE", "HEAT_LEGGINGS", "HEAT_BOOTS"],
        &["GLACITE_HELMET", "GLACITE_CHESTPLATE", "GLACITE_LEGGINGS", "GLACITE_BOOTS"]
    ],
    equipment: &[
        &["DIVAN_PENDANT"],
        &["AMBER_NECKLACE", "SAPPHIRE_CLOAK", "JADE_BELT", "AMETHYST_GAUNTLET"],
        &["", "", "", "DWARVEN_HANDWARMERS"],
        &["TITANIUM_NECKLACE", "TITANIUM_CLOAK", "TITANIUM_BELT", "TITANIUM_GAUNTLET"],
        &["MITHRIL_NECKLACE", "MITHRIL_CLOAK", "MITHRIL_BELT", "MITHRIL_GAUNTLET"]
    ],
    tools: &[&["DIVAN_DRILL", "TITANIUM_DRILL_4", "TITANIUM_DRILL_3", "GEMSTONE_GAUNTLET", "GEMSTONE_DRILL_4", "TITANIUM_DRILL_2",
        "GEMSTONE_DRILL_3", "TITANIUM_DRILL_1", "GEMSTONE_DRILL_2", "GEMSTONE_DRILL_1", "MITHRIL_DRILL_2", "MITHRIL_DRILL_1"]],
    pets: &["SCATHA", "GLACITE_GOLEM", "BAL", "MOLE", "SILVERFISH"],
};

pub const FARMING_SETUP: Setup = Setup {
    armor: &[
        &["", "", "", "RANCHERS_BOOTS"],
        &["FERMENTO_HELMET", "FERMENTO_CHESTPLATE", "FERMENTO_LEGGINGS", "FERMENTO_BOOTS"],
        &["SQUASH_HELMET", "SQUASH_CHESTPLATE", "SQUASH_LEGGINGS", "SQUASH_BOOTS"],
        &["CROPIE_HELMET", "CROPIE_CHESTPLATE", "CROPIE_CHESTPLATE", "CROPIE_BOOTS"],
        &["MELON_HELMET", "MELON_CHESTPLATE", "MELON_LEGGINGS", "MELON_BOOTS"],
        &["FARM_ARMOR_HELMET", "FARM_ARMOR_CHESTPLATE", "FARM_ARMOR_LEGGINGS", "FARM_ARMOR_BOOTS"],
        &["FARM_SUIT_HELMET", "FARM_SUIT_CHESTPLATE", "FARM_SUIT_LEGGINGS", "FARM_SUIT_BOOTS"]
    ],
    equipment: &[
        &["", "ZORROS_CAPE"],
        &["LOTUS_NECKLACE", "LOTUS_CLOAK", "LOTUS_BELT", "LOTUS_BRACELET"]
    ],
    tools: &[
        &["THEORETICAL_HOE_WHEAT_3", "THEORETICAL_HOE_WHEAT_2", "THEORETICAL_HOE_WHEAT_1"],
        &["THEORETICAL_HOE_CARROT_3", "THEORETICAL_HOE_CARROT_2", "THEORETICAL_HOE_CARROT_1"],
        &["THEORETICAL_HOE_POTATO_3", "THEORETICAL_HOE_POTATO_2", "THEORETICAL_HOE_POTATO_1"],
        &["THEORETICAL_HOE_WARTS_3", "THEORETICAL_HOE_WARTS_2", "THEORETICAL_HOE_WARTS_1"],
        &["THEORETICAL_HOE_CANE_3", "THEORETICAL_HOE_CANE_2", "THEORETICAL_HOE_CANE_1"],
        &["MELON_DICER_3", "MELON_DICER_2", "MELON_DICER"],
        &["PUMPKIN_DICER_3", "PUMPKIN_DICER_2", "PUMPKIN_DICER"],
        &["COCO_CHOPPER"],
        &["CACTUS_KNIFE"],
        &["FUNGI_CUTTER"]
    ],
    pets: &["ELEPHANT", "MOOSHROOM_COW", "HEDGEHOG", "SLUG", "MOSQUITO", "RABBIT"],
};

pub const FORAGING_SETUP: Setup = Setup {
    armor: &[
        &["FIG_HELMET", "FIG_CHESTPLATE", "FIG_LEGGINGS", "FIG_BOOTS"],
        &["CANOPY_HELMET", "CANOPY_CHESTPLATE", "CANOPY_LEGGINGS", "CANOPY_BOOTS"],
        &["MOLE_HAT", "KELLY_TSHIRT", "CHARLIE_TROUSERS", "MELODY_SHOES"],
    ],
    equipment: &[&["MANGROVE_LOCKET", "DAVIDS_CLOAK", "MANGROVE_VINE", "MANGROVE_GRIPPERS"]],
    tools: &[&["FIGSTONE_AXE", "TREECAPITATOR_AXE", "FIG_AXE", "JUNGLE_AXE", "PROMISING_AXE"]],
    pets: &["JADE_DRAGON", "FROG", "MONKEY", "OCELOT"],
};

pub const FISHING_SETUP: Setup = Setup {
    armor: &[
        &["MAGMA_LORD_HELMET", "MAGMA_LORD_CHESTPLATE", "MAGMA_LORD_LEGGINGS", "MAGMA_LORD_BOOTS"],
        &["THUNDER_HELMET", "THUNDER_CHESTPLATE", "THUNDER_LEGGINGS", "THUNDER_BOOTS"],
        &["TAURUS_HELMET", "FLAMING_CHESTPLATE", "MOOGMA_LEGGINGS", "SLUG_BOOTS"],
        &["SHARK_SCALE_HELMET", "SHARK_SCALE_CHESTPLATE", "SHARK_SCALE_LEGGINGS", "SHARK_SCALE_BOOTS"],
        &["ABYSSAL_HELMET", "ABYSSAL_CHESTPLATE", "ABYSSAL_LEGGINGS", "ABYSSAL_BOOTS"],
        &["DIVER_HELMET", "DIVER_CHESTPLATE", "DIVER_LEGGINGS", "DIVER_BOOTS"],
        &["SPONGE_HELMET", "SPONGE_CHESTPLATE", "SPONGE_LEGGINGS", "SPONGE_BOOTS"],
        &["NUTCRACKER_HELMET", "NUTCRACKER_CHESTPLATE", "NUTCRACKER_LEGGINGS", "NUTCRACKER_BOOTS"],
        &["WATER_HYDRA_HEAD"],
        &["SALMON_HELMET_NEW", "SALMON_CHESTPLATE_NEW", "SALMON_LEGGINGS_NEW", "SALMON_BOOTS_NEW"],
        &["BACKWATER_HELMET", "BACKWATER_CHESTPLATE", "BACKWATER_LEGGINGS", "BACKWATER_BOOTS"],
        &["ANGLER_HELMET", "ANGLER_CHESTPLATE", "ANGLER_LEGGINGS", "ANGLER_BOOTS"]
    ],
    equipment: &[
        &["", "GILLSPLASH_CLOAK", "GILLSPLASH_BELT", "GILLSPLASH_GLOVES"],
        &["", "FINWAVE_CLOAK", "FINWAVE_BELT", "FINWAVE_GLOVES"],
        &["", "ICHTHYIC_CLOAK", "ICHTHYIC_BELT", "ICHTHYIC_GLOVES"],
        &["THUNDERBOLT_NECKLACE"],
        &["DELIRIUM_NECKLACE"],
        &["BACKWATER_NECKLACE", "BACKWATER_CLOAK", "BACKWATER_BELT", "BACKWATER_GLOVES"],
        &["PRISMARINE_NECKLACE", "CLOWNFISH_CLOAK", "SPONGE_BELT", "CLAY_BRACELET"],
        &["", "", "", "LUMINOUS_BRACELET"]
    ],
    tools: &[
        &["ROD_OF_THE_SEA", "LEGEND_ROD", "CHAMP_ROD", "CHALLENGE_ROD"],
        &["HELLFIRE_ROD", "INFERNO_ROD", "MAGMA_ROD", "POLISHED_TOPAZ_ROD", "STARTER_LAVA_ROD"]
    ],
    pets: &["FLYING_FISH", "HERMIT_CRAB", "SQUID", "AMMONITE", "MEGALODON", "REINDEER", "DOLPHIN"],
};

const DUNGEON_EQUIPMENT: &[&str; 4] = &["BONE_NECKLACE", "SHADOW_ASSASSIN_CLOAK", "ADAPTIVE_BELT", "SOULWEAVER_GLOVES"];

pub const ARCHER_SETUP: Setup = Setup {
    armor: &[
        &["POWER_WITHER_HELMET", "POWER_WITHER_CHESTPLATE", "POWER_WITHER_LEGGINGS", "POWER_WITHER_BOOTS"],
        &["SPEED_WITHER_HELMET", "SPEED_WITHER_CHESTPLATE", "SPEED_WITHER_LEGGINGS", "SPEED_WITHER_BOOTS"],
        &["FROZEN_BLAZE_HELMET", "FROZEN_BLAZE_CHESTPLATE", "FROZEN_BLAZE_LEGGINGS", "FROZEN_BLAZE_BOOTS"],
        &["NECROMANCER_LORD_HELMET", "NECROMANCER_LORD_CHESTPLATE", "NECROMANCER_LORD_LEGGINGS", "NECROMANCER_LORD_BOOTS"],
        &["SHADOW_ASSASSIN_HELMET", "SHADOW_ASSASSIN_CHESTPLATE", "SHADOW_ASSASSIN_LEGGINGS", "SHADOW_ASSASSIN_BOOTS"],
        &["STRONG_DRAGON_HELMET", "STRONG_DRAGON_CHESTPLATE", "STRONG_DRAGON_LEGGINGS", "STRONG_DRAGON_BOOTS"],
        &["YOUNG_DRAGON_HELMET", "YOUNG_DRAGON_CHESTPLATE", "YOUNG_DRAGON_LEGGINGS", "YOUNG_DRAGON_BOOTS"],
        &["UNSTABLE_DRAGON_HELMET", "UNSTABLE_DRAGON_CHESTPLATE", "UNSTABLE_DRAGON_LEGGINGS", "UNSTABLE_DRAGON_BOOTS"]
    ],
    equipment: &[DUNGEON_EQUIPMENT],
    tools: &[&["TERMINATOR", "MOSQUITO_BOW", "JUJU_SHORTBOW", "ITEM_SPIRIT_BOW"]],
    pets: &["GOLDEN_DRAGON", "ENDER_DRAGON", "WITHER_SKELETON", "SKELETON", "BABY_YETI", "LION", "TIGER"],
};

pub const BERSERKER_SETUP: Setup = Setup {
    armor: &[
        &["POWER_WITHER_HELMET", "POWER_WITHER_CHESTPLATE", "POWER_WITHER_LEGGINGS", "POWER_WITHER_BOOTS"],
        &["FROZEN_BLAZE_HELMET", "FROZEN_BLAZE_CHESTPLATE", "FROZEN_BLAZE_LEGGINGS", "FROZEN_BLAZE_BOOTS"],
        &["NECROMANCER_LORD_HELMET", "NECROMANCER_LORD_CHESTPLATE", "NECROMANCER_LORD_LEGGINGS", "NECROMANCER_LORD_BOOTS"],
        &["SHADOW_ASSASSIN_HELMET", "SHADOW_ASSASSIN_CHESTPLATE", "SHADOW_ASSASSIN_LEGGINGS", "SHADOW_ASSASSIN_BOOTS"],
        &["STRONG_DRAGON_HELMET", "STRONG_DRAGON_CHESTPLATE", "STRONG_DRAGON_LEGGINGS", "STRONG_DRAGON_BOOTS"],
        &["YOUNG_DRAGON_HELMET", "YOUNG_DRAGON_CHESTPLATE", "YOUNG_DRAGON_LEGGINGS", "YOUNG_DRAGON_BOOTS"],
        &["UNSTABLE_DRAGON_HELMET", "UNSTABLE_DRAGON_CHESTPLATE", "UNSTABLE_DRAGON_LEGGINGS", "UNSTABLE_DRAGON_BOOTS"]
    ],
    equipment: &[DUNGEON_EQUIPMENT],
    tools: &[&["DARK_CLAYMORE", "GIANTS_SWORD", "FELTHORN_REAPER", "SHADOW_FURY", "BOUQUET_OF_LIES", "LIVID_DAGGER", "FLOWER_OF_TRUTH"]],
    pets: &["GOLDEN_DRAGON", "ENDER_DRAGON", "BABY_YETI", "LION", "TIGER", "WITHER_SKELETON"],
};

pub const MAGE_SETUP: Setup = Setup {
    armor: &[
        &["WITHER_GOGGLES"],
        &["WISE_WITHER_HELMET", "WISE_WITHER_CHESTPLATE", "WISE_WITHER_LEGGINGS", "WISE_WITHER_BOOTS"],
        &["POWER_WITHER_HELMET", "POWER_WITHER_CHESTPLATE", "POWER_WITHER_LEGGINGS", "POWER_WITHER_BOOTS"],
        &["SHADOW_GOGGLES"],
        &["DARK_GOGGLES"],
        &["WISE_DRAGON_HELMET", "WISE_DRAGON_CHESTPLATE", "WISE_DRAGON_LEGGINGS", "WISE_DRAGON_BOOTS"]
    ],
    equipment: &[
        &["MOLTEN_NECKLACE", "", "IMPLOSION_BELT", "GAUNTLET_OF_CONTAGION"],
        DUNGEON_EQUIPMENT,
        &["VANQUISHED_BLAZE_BELT", "VANQUISHED_GHAST_CLOAK", "VANQUISHED_MAGMA_NECKLACE", "VANQUISHED_GLOWSTONE_GAUNTLET"],
        &["BLAZE_BELT", "GHAST_CLOAK", "MAGMA_NECKLACE", "GLOWSTONE_GAUNTLET"],
    ],
    tools: &[&["HYPERION", "TERMINATOR", "MIDAS_STAFF", "DARK_CLAYMORE", "GIANTS_SWORD", "YETI_SWORD", "GLACIAL_SCYTHE", "BAT_WAND", "FROZEN_SCYTHE"]],
    pets: &["GOLDEN_DRAGON", "SHEEP", "ENDER_DRAGON"],
};

pub const TANK_SETUP: Setup = Setup {
    armor: &[
        &["REAPER_MASK"],
        &["TANK_WITHER_HELMET", "TANK_WITHER_CHESTPLATE", "TANK_WITHER_LEGGINGS", "TANK_WITHER_BOOTS"],
        &["POWER_WITHER_HELMET", "POWER_WITHER_CHESTPLATE", "POWER_WITHER_LEGGINGS", "POWER_WITHER_BOOTS"],
        &["FROZEN_BLAZE_HELMET", "FROZEN_BLAZE_CHESTPLATE", "FROZEN_BLAZE_LEGGINGS", "FROZEN_BLAZE_BOOTS"],
        &["NECROMANCER_LORD_HELMET", "NECROMANCER_LORD_CHESTPLATE", "NECROMANCER_LORD_LEGGINGS", "NECROMANCER_LORD_BOOTS"],
        &["SHADOW_ASSASSIN_HELMET", "SHADOW_ASSASSIN_CHESTPLATE", "SHADOW_ASSASSIN_LEGGINGS", "SHADOW_ASSASSIN_BOOTS"],
        &["STRONG_DRAGON_HELMET", "STRONG_DRAGON_CHESTPLATE", "STRONG_DRAGON_LEGGINGS", "STRONG_DRAGON_BOOTS"],
        &["PROTECTOR_DRAGON_HELMET", "PROTECTOR_DRAGON_CHESTPLATE", "PROTECTOR_DRAGON_LEGGINGS", "PROTECTOR_DRAGON_BOOTS"],
        &["OLD_DRAGON_HELMET", "OLD_DRAGON_CHESTPLATE", "OLD_DRAGON_LEGGINGS", "OLD_DRAGON_BOOTS"],
        &["HOLY_DRAGON_HELMET", "HOLY_DRAGON_CHESTPLATE", "HOLY_DRAGON_LEGGINGS", "HOLY_DRAGON_BOOTS"]
    ],
    equipment: &[DUNGEON_EQUIPMENT],
    tools: &[&["TERMINATOR", "HYPERION", "VALKYRIE", "ASTRAEA", "SCYLLA", "DARK_CLAYMORE", "GIANTS_SWORD",
        "MOSQUITO_BOW", "JUJU_SHORTBOW", "FELTHORN_REAPER", "SHADOW_FURY", "BOUQUET_OF_LIES", "LIVID_DAGGER"]],
    pets: &["GOLDEN_DRAGON", "ENDER_DRAGON", "BABY_YETI", "BLUE_WHALE", "TURTLE"],
};

pub const HEALER_SETUP: Setup = Setup {
    armor: &[
        &["REAPER_MASK"],
        &["MENDER_CROWN"],
        &["TANK_WITHER_HELMET", "TANK_WITHER_CHESTPLATE", "TANK_WITHER_LEGGINGS", "TANK_WITHER_BOOTS"],
        &["POWER_WITHER_HELMET", "POWER_WITHER_CHESTPLATE", "POWER_WITHER_LEGGINGS", "POWER_WITHER_BOOTS"],
        &["FROZEN_BLAZE_HELMET", "FROZEN_BLAZE_CHESTPLATE", "FROZEN_BLAZE_LEGGINGS", "FROZEN_BLAZE_BOOTS"],
        &["SHADOW_ASSASSIN_HELMET", "SHADOW_ASSASSIN_CHESTPLATE", "SHADOW_ASSASSIN_LEGGINGS", "SHADOW_ASSASSIN_BOOTS"],
        &["MENDER_FEDORA"],
        &["MENDER_HELMET"],
        &["STRONG_DRAGON_HELMET", "STRONG_DRAGON_CHESTPLATE", "STRONG_DRAGON_LEGGINGS", "STRONG_DRAGON_BOOTS"],
        &["HOLY_DRAGON_HELMET", "HOLY_DRAGON_CHESTPLATE", "HOLY_DRAGON_LEGGINGS", "HOLY_DRAGON_BOOTS"],
        &["OLD_DRAGON_HELMET", "OLD_DRAGON_CHESTPLATE", "OLD_DRAGON_LEGGINGS", "OLD_DRAGON_BOOTS"],
        &["PROTECTOR_DRAGON_HELMET", "PROTECTOR_DRAGON_CHESTPLATE", "PROTECTOR_DRAGON_LEGGINGS", "PROTECTOR_DRAGON_BOOTS"]
    ],
    equipment: &[DUNGEON_EQUIPMENT],
    tools: &[&["TERMINATOR", "HYPERION", "VALKYRIE", "ASTRAEA", "SCYLLA", "DARK_CLAYMORE", "GIANTS_SWORD",
        "MOSQUITO_BOW", "JUJU_SHORTBOW", "FELTHORN_REAPER", "SHADOW_FURY", "BOUQUET_OF_LIES", "LIVID_DAGGER"]],
    pets: &["GOLDEN_DRAGON", "ENDER_DRAGON", "BABY_YETI", "BLUE_WHALE", "TURTLE"],
};